"""Setup de Alembic: env.py conectado a Settings + Base.metadata, migraciones
aplicables y reversibles (`documentacion/02_Documento_Tecnico.md` §23)."""

from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory

ALEMBIC_INI = Path(__file__).resolve().parents[2] / "alembic.ini"


def _config(url: str) -> Config:
    cfg = Config(str(ALEMBIC_INI))
    cfg.set_main_option("sqlalchemy.url", url)
    return cfg


def test_ini_has_no_hardcoded_url():
    cfg = Config(str(ALEMBIC_INI))
    assert not (cfg.get_main_option("sqlalchemy.url") or "").strip()


def test_single_head_and_single_base():
    script = ScriptDirectory.from_config(_config("sqlite://"))
    assert len(script.get_heads()) == 1, "debe haber exactamente un head"
    assert len(script.get_bases()) == 1, "debe haber exactamente una migración raíz"


def test_baseline_is_root_and_empty():
    script = ScriptDirectory.from_config(_config("sqlite://"))
    base_rev = script.get_bases()[0]
    revision = script.get_revision(base_rev)
    assert revision.down_revision is None


def test_upgrade_then_downgrade_on_temp_db(tmp_path: Path):
    url = f"sqlite:///{(tmp_path / 'm.db').as_posix()}"
    cfg = _config(url)
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")  # el downgrade no debe dejarla en un estado roto


def test_head_matches_models_no_pending_diffs(tmp_path: Path):
    """`Base.metadata` (todos los modelos, vía `app.models`) y el head de
    Alembic tienen que coincidir: ningún modelo debería quedar sin su
    migración. Si este test falla, falta un `alembic revision --autogenerate`."""
    url = f"sqlite:///{(tmp_path / 'chk.db').as_posix()}"
    cfg = _config(url)
    command.upgrade(cfg, "head")
    command.check(cfg)  # lanza AutogenerateDiffsDetected si hay diffs pendientes
