"""fase1 audit log

Revision ID: 06dc33053727
Revises: 1e932d246e38
Create Date: 2026-09-11 09:16:02.592553

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Los modelos usan tipos propios (UtcDateTime, sa_enum) de app.db.types; el
# autogenerate de Alembic no agrega este import solo, así que va siempre acá.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = "06dc33053727"
down_revision: Union[str, Sequence[str], None] = "1e932d246e38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=80), nullable=False),
        sa.Column("data", sa.Text(), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("created_at", app.db.types.UtcDateTime(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_log_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_entity", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_actor_id"), ["actor_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_actor_id"))
        batch_op.drop_index("ix_audit_entity")

    op.drop_table("audit_log")
    # ### end Alembic commands ###
