"""fase1 revoked tokens

Revision ID: 1e932d246e38
Revises: d05cdcbf4e55
Create Date: 2026-09-11 08:37:19.080790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Los modelos usan tipos propios (UtcDateTime, sa_enum) de app.db.types; el
# autogenerate de Alembic no agrega este import solo, así que va siempre acá.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = "1e932d246e38"
down_revision: Union[str, Sequence[str], None] = "d05cdcbf4e55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revoked_tokens",
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("expires_at", app.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("revoked_at", app.db.types.UtcDateTime(length=32), nullable=False),
        sa.PrimaryKeyConstraint("jti", name=op.f("pk_revoked_tokens")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("revoked_tokens")
    # ### end Alembic commands ###
