"""fase2 system settings

Revision ID: 4ce9a2ce1a9f
Revises: 06dc33053727
Create Date: 2026-09-11 21:34:47.088852

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Los modelos usan tipos propios (UtcDateTime, sa_enum) de app.db.types; el
# autogenerate de Alembic no agrega este import solo, así que va siempre acá.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = "4ce9a2ce1a9f"
down_revision: Union[str, Sequence[str], None] = "06dc33053727"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "value_type",
            sa.Enum(
                "json",
                "string",
                "int",
                "bool",
                name="settingvaluetype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_at", app.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_system_settings_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_system_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("system_settings")
    # ### end Alembic commands ###
