"""fase2 shifts

Revision ID: ae71f966d5de
Revises: 4ce9a2ce1a9f
Create Date: 2026-09-11 22:37:08.466600

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Los modelos usan tipos propios (UtcDateTime, sa_enum) de app.db.types; el
# autogenerate de Alembic no agrega este import solo, así que va siempre acá.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = "ae71f966d5de"
down_revision: Union[str, Sequence[str], None] = "4ce9a2ce1a9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shifts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_date", sa.String(length=10), nullable=False),
        sa.Column(
            "service_type",
            sa.Enum(
                "BREAKFAST",
                "LUNCH",
                "DINNER",
                name="servicetype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("open_time", sa.String(length=5), nullable=False),
        sa.Column("close_time", sa.String(length=5), nullable=False),
        sa.Column("prep_eta", sa.String(length=5), nullable=True),
        sa.Column("dispatch_eta", sa.String(length=5), nullable=True),
        sa.Column("cancel_window_min", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "OPEN",
                "CLOSED",
                "IN_PRODUCTION",
                "DISPATCHING",
                "FINISHED",
                name="shiftstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("created_at", app.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("updated_at", app.db.types.UtcDateTime(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shifts")),
        sa.UniqueConstraint("service_date", "service_type", name=op.f("uq_shifts_service_date")),
    )
    with op.batch_alter_table("shifts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shifts_service_date"), ["service_date"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shifts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shifts_service_date"))

    op.drop_table("shifts")
    # ### end Alembic commands ###
