"""shifts

Revision ID: bd8b80aca114
Revises: 91da6202efd6
Create Date: 2026-09-24 19:54:21.534241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8b80aca114'
down_revision: Union[str, Sequence[str], None] = '91da6202efd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('service_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', name='service_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('open_time', sa.String(), nullable=False),
    sa.Column('close_time', sa.String(), nullable=False),
    sa.Column('prep_eta', sa.String(), nullable=True),
    sa.Column('dispatch_eta', sa.String(), nullable=True),
    sa.Column('cancel_window_min', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'OPEN', 'CLOSED', 'IN_PRODUCTION', 'DISPATCHING', 'FINISHED', name='shift_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('cancel_window_min >= 0', name=op.f('ck_shifts_cancel_window_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts')),
    sa.UniqueConstraint('service_date', 'service_type', name='uq_shifts_date_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shifts')
    # ### end Alembic commands ###
