"""shift closed effects marker

Revision ID: fc1ed56c4a3d
Revises: bd8b80aca114
Create Date: 2026-09-24 20:29:30.674156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1ed56c4a3d'
down_revision: Union[str, Sequence[str], None] = 'bd8b80aca114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_effects_applied_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_column('closed_effects_applied_at')

    # ### end Alembic commands ###
